# This is a GitHub Action workflow file.
# It defines a set of automated steps that will run every time you push to your master branch.

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # This workflow runs only when you push to the 'master' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a standard Linux environment for the build

    steps:
      - name: Checkout code
        # This step checks out a copy of your repository's code.
        uses: actions/checkout@v3

      - name: Create Firebase config file
        # This is the key step. It creates the firebase-config.js file on the fly.
        run: |
          # It reads the FIREBASE_CONFIG secret you created and writes its content
          # into a new file named firebase-config.js in the root of your project.
          echo "${{ secrets.FIREBASE_CONFIG }}" > firebase-config.js
        # The ${{ secrets.FIREBASE_CONFIG }} syntax is how you access the secret you stored.
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

      - name: Deploy to GitHub Pages
        # This step takes all the files (including the newly created config file)
        # and deploys them to the special 'gh-pages' branch, which is what your
        # live site is served from.
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Deploy the entire root directory
