name: Generate Sitemap

on:
  push:
    branches:
      - main # Or whichever branch you push to

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          # Use your full website URL here
          base-url-path: https://namethatyankeequiz.com

      - name: Commit and push sitemap
        uses: EndBug/add-and-commit@v9
        with:
          add: 'sitemap.xml'
          message: 'Update sitemap.xml'
          author_name: GitHub Actions
          author_email: actions@github.com
